#
#
#
# ██╗  ██╗██╗████████╗████████╗██╗   ██╗
# ██║ ██╔╝██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
# █████╔╝ ██║   ██║      ██║    ╚████╔╝
# ██╔═██╗ ██║   ██║      ██║     ╚██╔╝
# ██║  ██╗██║   ██║      ██║      ██║
# ╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝
#
# THEME
#
    include theme.conf
    term xterm-kitty
#
# SYSTEM CONFIGURATION
#
    linux_display_server wayland
    allow_remote_control yes
    allow_hyperlinks yes
    shell_integration enabled
    enable_graphics yes
    protocol file
    mime image/*
    action launch --type=overlay kitty +kitten icat --hold ${FILE_PATH}
#
# BACKGROUND
    background_opacity 0.77
    background_image_linear no
    dynamic_background_opacity yes
#
# FONTS
#
    font_size 11
    font_family      family='JetBrainsMono Nerd Font' style=Thin
    italic_font      family='JetBrainsMono Nerd Font' style='Light Italic'
    bold_font        auto
    bold_italic_font auto
#
# CURSOR
#
    disable_ligatures cursor
    cursor #dddddd
    cursor none
    cursor_beam_thickness 1
    cursor_trail 1
#
# MOUSE
#
    url_color #415c6d
    url_style curly
#
# TERMINAL BELL
#
    enable_audio_bell no
    visual_bell_color #859289
#
# SYNCING
#
    sync_to_monitor yes

# KEYBOARD SHORTCUTS
#
    kitty_mod ctrl+shift
#
# CLIPBOARD
#
    map ctrl+shift+c copy_to_clipboard
    map ctrl+shift+v paste_from_clipboard
    map ctrl+shift+y kitten hints --type url --program 'sh -c '\''printf "%s" "$1" | wl-clipboard && notify-send copied'\'' sh'
#
# SCROLLING
#
    scrollback_lines 99999
    wheel_scroll_min_lines 1
#
# TAB MANAGEMENT
#
    kitty @ set-tab-title $(/home/tomaking/.config/kitty/emoji.sh)
#
# Window
#
    window_padding_width 1
    confirm_os_window_close 0
    hide_window_decorations yes
#
# Tabs in Kitty
#
    # Neuen Tab erstellen   Ctrl+Shift+T        → Ctrl+Shift+T (unverändert, da T kein Modifier ist)
    # Nächsten Tab          Ctrl+Shift+Right    → Ctrl+Shift+Right
    # Vorherigen Tab        Ctrl+Shift+Left     → Ctrl+Shift+Left
    # Zu Tab 1..9 springen  Ctrl+Shift+1 … 9    → Ctrl+Shift+1 … 9
    # Tab schließen         Ctrl+Shift+Q        → Ctrl+Shift+Q
    # Tab umbenennen        Ctrl+Shift+Alt+T    → Ctrl+Shift+Alt+T
#
#
#
