#
#
#
# ██╗  ██╗██╗████████╗████████╗██╗   ██╗
# ██║ ██╔╝██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
# █████╔╝ ██║   ██║      ██║    ╚████╔╝
# ██╔═██╗ ██║   ██║      ██║     ╚██╔╝
# ██║  ██╗██║   ██║      ██║      ██║
# ╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝
#
# The basic colors
#
    foreground              #00FF00   # NeonGrün
    background              #000000   # NeonBlack
    selection_foreground    #00FF00
    selection_background    #FF5C00
#
# Cursor colors
#
    cursor                  #00FF00   # NeonGrün
    cursor_text_color       #74ee15
#
# URL underline color when hovering with mouse
#
    url_color               #0000FF   # NeonBlau
#
# OS Window titlebar colors
#
    wayland_titlebar_color system
    macos_titlebar_color system
#
# Tab bar colors
#
    active_tab_foreground   #00FF00   # NeonGrün
    active_tab_background   #FF0000   # NeonRot
    inactive_tab_foreground #00FEFC   # NeonTürkis (Cyan)
    inactive_tab_background #1a1a1a
    tab_bar_background      #000000
#
# The 16 terminal colors
#
    color0  #000000   # Black       (NeonBlack)
    color1  #FF0000   # Red         (NeonRot)
    color2  #00FF00   # Green       (NeonGrün)
    color3  #FFFF00   # Yellow      (NeonGelb)
    color4  #0000FF   # Blue        (NeonBlau)
    color5  #ff00a9   # Magenta     (NeonMagenta)
    color6  #00FEFC   # Cyan        (NeonTürkis)
    color7  #FFFFFF   # White       (NeonWeiß)
#
    color8  #333333   # Bright Black
    color9  #FF0000   # Bright Red
    color10 #00FF00   # Bright Green
    color11 #FFFF00   # Bright Yellow
    color12 #0000FF   # Bright Blue
    color13 #ff00a9   # Bright Magenta
    color14 #00FEFC   # Bright Cyan
    color15 #FFFFFF   # Bright White
#
#
#