#
#
#
# ██████╗ ████████╗ ██████╗ ██████╗ 
# ██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗
# ██████╔╝   ██║   ██║   ██║██████╔╝
# ██╔══██╗   ██║   ██║   ██║██╔═══╝ 
# ██████╔╝   ██║   ╚██████╔╝██║     
# ╚═════╝    ╚═╝    ╚═════╝ ╚═╝     
#
	# Aktualisierungsrate (Standard 2000 ms = 2 Sek.)
	update_ms = 1000               # flüssiger
	# Abgerundete Ecken
	rounded_corners = True
	# CPU‑Darstellung: einzelne Kerne anzeigen
	show_cpu_freq = True
	show_cpu_temp = True           # Temperatur direkt im CPU‑Block
	# Netzwerk‑Graphen in MBit/s statt MB/s
	net_auto = True                # automatische Einheit (kbps, Mbps)
	# Graphen‑Symbole: "block", "tty" oder "braille"
	graph_symbol = "block"         # füllt Balken vollständig – intensiverer Look
	# Theme setzen
	color_theme = "Neon"
	# Zusätzliche Anzeigen
	show_gpu_info = True           # falls GPU‑Daten verfügbar
	show_uptime = True
	show_init_disks = True         # Zeigt Festplatten beim Start an
#
#
#